import type { ProjectContext } from '../types/index.js';

/**
 * Generate an AI Coding Agent oriented AGENTS.md.
 * Content is dynamically generated from scan results, kept concise and practical.
 */
export function renderAgents(context: ProjectContext): string {
  return [
    renderHeader(context),
    renderPurpose(),
    renderFirstReadingOrder(context),
    renderTaskRouting(context),
    renderHighSignalFiles(context),
    renderRules(context),
    renderUsuallyAvoid(context),
    renderOutOfScope(),
  ]
    .filter((section) => section.length > 0)
    .join('\n\n');
}

function renderHeader(context: ProjectContext): string {
  return [
    '# Agent Instructions',
    '',
    `> Auto-generated by RepoMapper CLI for \`${context.projectName}\``,
  ].join('\n');
}

function renderPurpose(): string {
  return [
    '## Purpose',
    '',
    'RepoMapper is a local MCP server for AI coding agents. It indexes repository structure locally and exposes always-fresh tools for context, search, dependency fan-in/fan-out and impact analysis.',
    '',
    'This file is only a lightweight operating guide for agents. For live repository structure questions, prefer RepoMapper MCP tools over broad grep or reading unrelated files.',
  ].join('\n');
}

function renderFirstReadingOrder(context: ProjectContext): string {
  const candidates = [
    'README.md',
    'AGENTS.md',
    'package.json',
    'src/cli.ts',
    'src/mcp',
    'src/commands',
    'src/core',
    'src/detectors',
    'tests',
  ];

  const available = candidates.filter(
    (file) => context.scan.files.includes(file) || context.scan.directories.includes(file),
  );

  if (available.length === 0) {
    return '';
  }

  return [
    '## First Reading Order',
    '',
    'Read these files in order to understand the project before exploring further:',
    '',
    ...available.map((file, index) => `${index + 1}. \`${file}\``),
  ].join('\n');
}

function renderTaskRouting(context: ProjectContext): string {
  const rows = buildAgentRoutes(context);

  if (rows.length === 0) {
    return '';
  }

  return [
    '## Task Routing',
    '',
    '| Task | Start Here | Then Check | Avoid |',
    '|---|---|---|---|',
    ...rows.map((row) => `| ${row.task} | ${row.startHere} | ${row.thenCheck} | ${row.avoid} |`),
  ].join('\n');
}

function buildAgentRoutes(
  context: ProjectContext,
): Array<{ task: string; startHere: string; thenCheck: string; avoid: string }> {
  const rows: Array<{ task: string; startHere: string; thenCheck: string; avoid: string }> = [];
  const stack = new Set(context.detection.detectedTechStack);
  const has = (candidates: string[]) => candidates.some((candidate) => stack.has(candidate));

  addAgentRoute(
    rows,
    context,
    'Understand project',
    ['README.md', 'AGENTS.md'],
    ['package.json', 'src/cli.ts', 'src/mcp'],
    'node_modules, dist',
  );

  addAgentRoute(
    rows,
    context,
    'MCP tool behavior',
    ['src/mcp', 'src/mcp/server.ts'],
    ['src/mcp/handlers', 'src/mcp/cache.ts', 'tests/mcp-handlers.test.ts'],
    'dist, examples',
  );

  if (has(['React', 'Vite', 'Next.js', 'Vue']) || hasDirectory(context, 'frontend')) {
    addAgentRoute(
      rows,
      context,
      'Frontend UI change',
      ['frontend/src', 'frontend', 'src'],
      ['src/components', 'src/pages', 'package.json'],
      'backend, node_modules, dist',
    );
  }

  if (
    has(['Express', 'NestJS', 'Fastify']) ||
    hasDirectory(context, 'backend') ||
    hasFile(context, 'src/server.ts')
  ) {
    addAgentRoute(
      rows,
      context,
      'Backend API change',
      ['backend/src', 'backend', 'src/server.ts', 'src'],
      ['src/routes', 'src/controllers', 'src/services', 'package.json'],
      'frontend, node_modules, dist',
    );
  }

  addAgentRoute(
    rows,
    context,
    'Database change',
    ['prisma/schema.prisma'],
    ['src/services', 'src/types'],
    'node_modules, frontend',
  );
  addAgentRoute(
    rows,
    context,
    'CLI changes',
    ['src/cli.ts', 'src/commands'],
    ['tests', 'README.md'],
    'dist',
  );
  addAgentRoute(
    rows,
    context,
    'Detection logic',
    ['src/detectors', 'src/core/detector.ts'],
    ['tests/fixtures', 'tests'],
    'dist',
  );
  addAgentRoute(
    rows,
    context,
    'Configuration',
    ['src/core/config.ts', 'src/schema/config.ts', 'repomapper.config.json'],
    ['README.md', 'tests/config.test.ts'],
    'detectors',
  );
  addAgentRoute(
    rows,
    context,
    'Tests change',
    ['tests'],
    ['src/core', 'src/detectors', 'src/mcp'],
    'dist, build, coverage',
  );
  addAgentRoute(
    rows,
    context,
    'Documentation',
    ['README.md', 'README-zh-CN.md', 'docs'],
    ['package.json', 'src/mcp/instructions.ts'],
    'src, node_modules',
  );

  if (hasDirectory(context, 'tests') || hasTestFile(context)) {
    addAgentRoute(
      rows,
      context,
      'Run or add tests',
      ['tests'],
      ['src/core', 'package.json'],
      'dist, coverage',
    );
  }

  return rows;
}

function addAgentRoute(
  rows: Array<{ task: string; startHere: string; thenCheck: string; avoid: string }>,
  context: ProjectContext,
  task: string,
  startCandidates: string[],
  thenCandidates: string[],
  avoid: string,
): void {
  const match = findExisting(context, startCandidates);

  if (match === undefined) {
    return;
  }

  const thenCheck = thenCandidates
    .filter((candidate) => candidate !== match)
    .filter(
      (candidate) =>
        context.scan.files.includes(candidate) || context.scan.directories.includes(candidate),
    )
    .map((candidate) => `\`${candidate}\``)
    .join(', ');

  rows.push({
    task,
    startHere: `\`${match}\``,
    thenCheck: thenCheck || 'Related imports and adjacent config',
    avoid,
  });
}

function renderHighSignalFiles(context: ProjectContext): string {
  const entryPaths = context.detection.entryPoints.map((entry) => entry.path);
  const importantPaths = context.detection.importantFiles.map((file) => file.path);
  const keyPaths = context.scan.keyFiles;
  const candidates = [...entryPaths, ...importantPaths, ...keyPaths];
  const uniqueFiles = [...new Set(candidates)].filter((file) => context.scan.files.includes(file));
  const top = uniqueFiles.slice(0, 15);

  if (top.length === 0) {
    return '';
  }

  return ['## High-Signal Files', '', ...top.map((file) => `- \`${file}\``)].join('\n');
}

function renderRules(context: ProjectContext): string {
  const rules = [
    '- Use RepoMapper MCP tools for structural questions before broad grep or reading many files.',
    '- Do not inspect `node_modules/`, `dist/`, `coverage/` unless the task is specifically about those areas.',
    '- Only open files relevant to the current task.',
  ];

  if (hasDirectory(context, 'tests') || hasTestFile(context)) {
    rules.push('- For detector and MCP behavior changes, update fixtures and tests.');
  }

  rules.push('- Run `pnpm check` (or equivalent) before finalizing.');

  return ['## Rules for Agents', '', ...rules].join('\n');
}

function renderUsuallyAvoid(context: ProjectContext): string {
  const builtIn = [
    'node_modules',
    '.pnpm',
    '.yarn',
    'dist',
    'build',
    'coverage',
    '.git',
    '.next',
    '.turbo',
    '.vite',
    'target',
    '.cache',
  ];
  const configIgnore = context.config.ignore.filter((dir) => !builtIn.includes(dir));
  const all = [...new Set([...builtIn, ...configIgnore])];

  return [
    '## Usually Avoid',
    '',
    ...all.map((dir) => `- \`${dir}/\``),
    '- Lockfiles unless the task is about dependency resolution',
    '- Generated files unless the task is about generated output',
    '- Assets unless the task is about UI assets',
  ].join('\n');
}

function renderOutOfScope(): string {
  return [
    '## Out of Scope',
    '',
    'RepoMapper does not provide:',
    '',
    '- AI API or LLM integration',
    '- AST-level semantic code graph',
    '- Vector database or embeddings',
    '- Full language-server replacement',
    '- Benchmark claims without test evidence',
  ].join('\n');
}

function findExisting(context: ProjectContext, candidates: string[]): string | undefined {
  return candidates.find(
    (candidate) =>
      context.scan.files.includes(candidate) || context.scan.directories.includes(candidate),
  );
}

function hasDirectory(context: ProjectContext, dir: string): boolean {
  return context.scan.directories.includes(dir);
}

function hasFile(context: ProjectContext, file: string): boolean {
  return context.scan.files.includes(file);
}

function hasTestFile(context: ProjectContext): boolean {
  return context.scan.files.some((file) => /\.(test|spec)\.[cm]?[jt]sx?$/.test(file));
}
