export const REPOMAPPER_MCP_INSTRUCTIONS = [
  "You are connected to the RepoMapper index. For questions about repository structure, query these tools directly instead of grepping or reading files one by one — the index already did that work.",
  '你已连接 RepoMapper 索引。回答仓库结构性问题时直接查询这些工具，不要逐个 read 文件——索引已经做过这些工作。',
  '',
  'Pick a tool by intent / 按意图选工具：',
  '- "What is this project?" → repomapper_context (tech stack, entry points, important files, scripts). 「这个项目是什么」',
  '- "What does changing X affect?" → repomapper_impact (transitive dependents; depth default 2, raise minDepth or set limit when results are large; check totalImpacted/levelTotals first) or repomapper_dependents (direct dependents). 「改 X 会影响什么」',
  '- "How does a change in A reach B?" → repomapper_path_between (dependency chain from A to B). 「A 的改动怎么传导到 B」',
  '- "Where is X / who calls X?" → repomapper_search (kind=file|dir|symbol|all) to locate; repomapper_file_info for exports/symbols/imports/importedBy plus calls/calledBy with call-site line numbers (TS/JS exported functions). 「X 在哪 / 谁调用 X」',
  '- "Find this string / env var / route / TODO in code" → repomapper_grep (literal or regex content search, returns path+line+matching line). This is content search; the index does it for you, so prefer it over external grep. 「在代码内容里找某个字符串」',
  '- "What does X depend on?" → repomapper_imports (forward dependencies). 「X 依赖了什么」',
  '- "Core modules / where to start reading?" → repomapper_hubs. 「核心模块 / 从哪读起」',
  '- "What does the tree look like?" → repomapper_tree (scope with path/depth). 「目录长什么样」',
  '- "Is the index up to date?" → repomapper_status; if status.nextAction === "call_refresh", call repomapper_refresh and wait before trusting results. 「索引是否最新」',
  '',
  'Boundaries / 边界:',
  '- import graph is file-level, covering TS/JS, Python and Go; NodeNext .js imports resolve back to source files. 文件级 import 图覆盖 TS/JS、Python、Go。',
  '- call graph is regex-level for exported TS/JS functions, NOT a full AST. An empty calledBy does not prove a symbol is unused (internal/dynamic/non-exported calls are not captured). call graph 是 regex 级 TS/JS 导出函数调用边，非完整 AST；calledBy 为空不代表真的无人调用。',
  '- list-style results (impact/dependents/imports) report total and truncated; use limit/offset to page. 列表结果带 total/truncated，可用 limit/offset 翻页。',
].join('\n');
