export const REPOMAPPER_MCP_INSTRUCTIONS = [
  "You are connected to the RepoMapper index. For questions about repository structure, query these tools directly instead of grepping or reading files one by one — the index already did that work.",
  '你已连接 RepoMapper 索引。回答仓库结构性问题时直接查询这些工具，不要逐个 read 文件——索引已经做过这些工作。',
  '',
  'Pick a tool by intent / 按意图选工具：',
  '- "What is this project?" → repomapper_context (tech stack, entry points, important files, scripts). 「这个项目是什么」',
  '- "What does changing X affect?" → repomapper_impact (transitive dependents; depth default 2, raise minDepth or set limit when results are large; check totalImpacted/levelTotals first) or repomapper_dependents (direct dependents). 「改 X 会影响什么」',
  '- "How does a change in A reach B?" → repomapper_path_between (reverse-dependency change propagation from A to B; for forward imports use repomapper_imports). 「A 的改动怎么传导到 B」',
  '- "Where is X / who calls X?" → repomapper_search (kind=file|dir|symbol|all; set contextLines for definition snippets) to locate; repomapper_file_info defaults to exports/symbols/imports/importedBy, so request fields:["callsByExport"] when you need calls/calledBy and best-effort importCallSites. 「X 在哪 / 谁调用 X」',
  '- "Need details for many files?" → repomapper_file_info_batch with fields to avoid oversized JSON; omit fields for lightweight defaults, use fields:[] only when you need the full legacy payload. 「要查多个文件详情」',
  '- "Find this string / env var / route / TODO in code" → repomapper_grep (literal or regex content search, returns path+line+matching line; use limit/offset for paging and contextLines when surrounding code matters). If repomapper_search returns no structural hits, switch to grep. 「在代码内容里找某个字符串」',
  '- "Read this file or line range" → repomapper_read_file (indexed repo-relative text files only; use startLine/endLine for a slice). 「读取文件或行范围」',
  '- "What does X depend on?" → repomapper_imports (forward dependencies). 「X 依赖了什么」',
  '- "Core modules / where to start reading?" → repomapper_context.recommendedNextReads for first-pass reading order, then repomapper_hubs for depended-on modules. 「核心模块 / 从哪读起」',
  '- "What does the tree look like?" → repomapper_tree (scope with path/depth; returns text tree plus structured entries; set fields:["entries"] or fields:["tree"] to reduce payload). 「目录长什么样」',
  '- "Is the index up to date?" → repomapper_status. 普通查询工具会自动刷新；if status.nextAction === "call_refresh", repomapper_refresh is useful only when you want to explicitly wait before another step. 「索引是否最新」',
  '',
  'Boundaries / 边界:',
  '- import graph is file-level, covering TS/JS, Python and Go; NodeNext .js imports resolve back to source files. 文件级 import 图覆盖 TS/JS、Python、Go。',
  '- call graph is regex-level for exported TS/JS functions, NOT a full AST. An empty calledBy does not prove a symbol is unused (internal/dynamic/non-exported calls are not captured). call graph 是 regex 级 TS/JS 导出函数调用边，非完整 AST；calledBy 为空不代表真的无人调用。',
  '- list-style results (grep/search/impact/dependents/imports) report total/truncated where applicable; use limit/offset to page. 列表结果尽量带 total/truncated，可用 limit/offset 翻页。',
  '- read_file and grep skip binary or oversized files; they are repository text helpers, not arbitrary filesystem readers. read_file 和 grep 会跳过二进制或超大文件；它们是仓库文本助手，不是任意文件系统读取器。',
].join('\n');
